name: Commit Message Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate commit messages
        run: |
          commits=$(git log ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} --pretty=format:"%s")

          while IFS= read -r commit; do
            echo "Verificando: $commit"

            if [[ ! "$commit" =~ ^(add|update|fix):\ .+ ]]; then
              echo "❌ Commit inválido: $commit"
              exit 1
            fi
          done <<< "$commits"

          echo "✅ Todos os commits estão válidos."